package pojlib.util;

public enum StaticProperty {
    MSA_MESSAGE,
    FINISHED_DOWNLOADING,
    IGNORE_INSTANCE_NAME,
    CUSTOM_RAM_VALUE,
    DOWNLOAD_STATUS,
    CURRENT_DOWNLOAD,
    PROFILE_IMAGE,
    PROFILE_NAME,
    MEMORY_VALUE,
    DEVELOPER_MODS,
    ADVANCED_DEBUGGER
}
